export const PUSH_TO_CART = 'PUSH_TO_CART';
export const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT';
export const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const TOGGLE_FAVORITES = 'ADD_TO_FAVORITES';

